spring:
  application:
    name: order
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
 
eureka:
  client:
    service-url:
      defaultZone: http://192.168.183.61:7000/eureka/
env: dev
